"""added username

Revision ID: 035718c5f755
Revises: eb1b191ec388
Create Date: 2023-07-01 21:59:04.015255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035718c5f755'
down_revision = 'eb1b191ec388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
